#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/product
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
        
spring:
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/product
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 10
    postgresql:
      url: jdbc:postgresql://localhost:5432/order
      username: killi
      password: post@123
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 10
        
  jpa:
    open-in-view: false
    generate-ddl: true # need to give this 
    mysql:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
    postgresql:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update